FROM node:24.11.1-alpine

WORKDIR /app

# Prisma needs openssl
RUN apk add --no-cache openssl

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Generate Prisma Client
RUN npx prisma generate
ENV NODE_ENV=production
RUN npm run builds
EXPOSE 3000

# Start Next.js in dev mode (hot reload)
CMD ["npm", "run", "dev"]
